// Sealed exchange: a question whose answers stay unreadable to both sides
// until both sides have answered.
//
// Every read here returns rows still sealed, the same contract
// `message-queries.ts` keeps, and for the same reason: opening needs an
// identity and a peer key that this module has no business holding.
//
// Nothing in this file enforces the withholding. It cannot — this repository
// is public, and a check that lives in the client is a check anyone can
// delete. The rule lives in the SELECT policy on `sealed_answers` (schema.sql
// section 5c), which hands you the peer's answer only once your own exists.
// What is here is the shape of the exchange as the UI needs to see it.

import { supabase } from './supabase';
import { openBody, sealBody } from './sealed-body';
import type { Identity } from './crypto/keys';
import type { Message } from './types';

/** An answer as stored: sealed, like every other body in this app. */
export interface SealedAnswerRow {
  id: string;
  prompt_id: string;
  user_id: string;
  ciphertext: string;
  nonce: string;
  created_at: string;
}

/** An answer after the decrypt boundary. `text` is null when this device
 *  could not open it, which renders as a warning rather than as silence. */
export interface OpenedAnswer {
  id: string;
  prompt_id: string;
  user_id: string;
  text: string | null;
  created_at: string;
}

/**
 * Where an exchange stands, from one participant's point of view.
 *
 * `awaiting_you` covers the case where the peer has answered and you have not:
 * their row exists but the policy does not release it, so from here it is
 * indistinguishable from them not having answered at all. That is the design
 * working, not a gap in it — knowing whether they have already answered would
 * itself be information about the order.
 */
export type ExchangeState = 'awaiting_you' | 'awaiting_peer' | 'revealed';

export function exchangeState(me: string, answers: OpenedAnswer[]): ExchangeState {
  const mine = answers.some((a) => a.user_id === me);
  if (!mine) return 'awaiting_you';
  return answers.some((a) => a.user_id !== me) ? 'revealed' : 'awaiting_peer';
}

/** Your own answer, and the peer's once it is readable. Split out because the
 *  card renders them in fixed positions rather than in arrival order. */
export function splitAnswers(me: string, answers: OpenedAnswer[]) {
  return {
    mine: answers.find((a) => a.user_id === me) ?? null,
    theirs: answers.find((a) => a.user_id !== me) ?? null,
  };
}

/** Every answer this account is allowed to see for these prompts. An empty
 *  list of ids is a no-op rather than a query for everything. */
export async function fetchAnswers(promptIds: string[]): Promise<SealedAnswerRow[]> {
  if (promptIds.length === 0) return [];
  const { data } = await supabase
    .from('sealed_answers')
    .select('*')
    .in('prompt_id', promptIds)
    .order('created_at', { ascending: true });
  return (data ?? []) as SealedAnswerRow[];
}

/**
 * Open an answer row.
 *
 * The row carries only its author, so the counterpart is supplied: an answer
 * is sealed `crypto_box` between the pair exactly like a body, and the box is
 * mutual, so either participant opens it with their own private key and the
 * other's public one. `openBody` wants both ids to make the self-chat
 * decision, which a sealed exchange can never be in — the CHECK constraint on
 * `sealed_prompt` forbids it.
 */
export async function openAnswer(
  identity: Identity,
  peerPublic: Uint8Array | null,
  me: string,
  peerId: string,
  row: SealedAnswerRow
): Promise<OpenedAnswer> {
  const text = await openBody(identity, peerPublic, {
    ciphertext: row.ciphertext,
    nonce: row.nonce,
    user_id: row.user_id,
    receiver_id: row.user_id === me ? peerId : me,
  });
  return { id: row.id, prompt_id: row.prompt_id, user_id: row.user_id, text, created_at: row.created_at };
}

/**
 * Ask a question and commit your own answer to it, in one transaction.
 *
 * Two inserts from the client would have a state between them where the
 * question exists and the asker has not answered it — the peer could answer
 * that, unlocking nothing, and be stuck with a permanent answer to a question
 * whose other half never arrives. `ask_sealed` is a plain SECURITY INVOKER
 * function, so every policy above still applies; what it buys is that both
 * rows land or neither does.
 *
 * `id` is generated by the caller, as the outbox does, so a retry after a lost
 * response collides on the primary key instead of asking twice.
 */
export async function askSealed(
  identity: Identity,
  peerPublic: Uint8Array | null,
  me: string,
  peerId: string,
  id: string,
  question: string,
  answer: string
): Promise<Message> {
  const prompt = await sealBody(identity, peerPublic, me, peerId, question);
  const mine = await sealBody(identity, peerPublic, me, peerId, answer);
  const { data, error } = await supabase.rpc('ask_sealed', {
    prompt_id: id,
    receiver: peerId,
    prompt_ciphertext: prompt.ciphertext,
    prompt_nonce: prompt.nonce,
    answer_ciphertext: mine.ciphertext,
    answer_nonce: mine.nonce,
  });
  if (error) throw error;
  return data as Message;
}

/**
 * Commit your answer. The reveal is what happens next and is not a separate
 * step: the moment this row exists the policy releases the other one, on both
 * devices.
 */
export async function answerSealed(
  identity: Identity,
  peerPublic: Uint8Array | null,
  me: string,
  peerId: string,
  promptId: string,
  answer: string
): Promise<void> {
  const sealed = await sealBody(identity, peerPublic, me, peerId, answer);
  const { error } = await supabase.from('sealed_answers').insert({
    prompt_id: promptId,
    user_id: me,
    ciphertext: sealed.ciphertext,
    nonce: sealed.nonce,
  });
  if (error) throw error;
}
