// What to do with an offer that just arrived.
//
// Split out of the provider because this is the whole of the interesting part
// and none of the untestable part: four things race here — the caller repeating
// its offer, the user answering, a socket rebuilding after the phone woke, and
// the other person hanging up — and getting the interleavings wrong is what put
// "On another call" on the caller's screen while the callee went on ringing.
// The provider keeps the refs and the peer connection; the decision is here,
// where the node suite can reach it.

import type { CallPhase } from './state';

export interface CallLike {
  phase: CallPhase;
  callId: string | null;
  peerId: string | null;
}

/** An offer we are holding: the one being rung, or the one we answered. */
export interface OfferRef {
  callId: string;
  peerId: string;
  sdp: string;
}

export type OfferAction =
  /** Nothing to do, and nothing to remember. */
  | 'ignore'
  /** The same call again. Keep the newer SDP; do not touch the connection. */
  | 'refresh'
  /** Our answer never reached them. Send it again. */
  | 'replay-answer'
  /** A real ICE restart on the live call — hand it to the peer connection. */
  | 'restart'
  /** A call we are not in. Ring. */
  | 'ring'
  /** We both dialled; we are the side that backs down and answers theirs. */
  | 'yield'
  /** Someone else, while we are on a call. */
  | 'busy';

/**
 * The `a=ice-ufrag` of an SDP, which is the name of its ICE session.
 *
 * The first one: with BUNDLE every m-section shares it, and without BUNDLE an
 * ICE restart changes all of them together, so the first is as good as the set.
 */
export function iceUfrag(sdp: string): string | null {
  const match = /^a=ice-ufrag:(\S+)/m.exec(sdp);
  return match ? match[1] : null;
}

/**
 * Whether two SDPs describe the same ICE session.
 *
 * **Not** whether they are the same string, which is what this used to be and
 * is the bug it exists to prevent. `repeatOffer` re-sends
 * `pc.localDescription.sdp`, and a browser adds each candidate to the local
 * description as it gathers it — so an unchanged offer, repeated two seconds
 * later, is a different string. Comparing text called every repeat a brand new
 * call from someone we were already engaged with, which is precisely the reply
 * "busy" is for.
 *
 * The ufrag is the right question: it is regenerated by an ICE restart and by
 * nothing else, which is the one case that really must reach the connection.
 * A payload with no ufrag to read is not SDP this app produced; comparing the
 * text is the safe answer there.
 */
export function sameIceSession(a: string, b: string): boolean {
  const left = iceUfrag(a);
  const right = iceUfrag(b);
  if (left === null || right === null) return a === b;
  return left === right;
}

export function routeOffer({
  state,
  pending,
  incoming,
  polite,
  connected = true,
}: {
  state: CallLike;
  /** The offer this device is already holding for a call, if any. */
  pending: OfferRef | null;
  incoming: OfferRef;
  /** `isPolite(me, peerId)` — which side backs down in a collision. */
  polite: boolean;
  /**
   * Whether there is a peer connection behind the call in state.
   *
   * False only in the lock-screen case: the call was answered before its offer
   * reached the device, so the phase is `connecting` with nothing to connect
   * yet. Defaulted to true because every other caller has a session by the time
   * it reaches a phase that could ask.
   */
  connected?: boolean;
}): OfferAction {
  const mine = state.callId === incoming.callId && state.peerId === incoming.peerId;
  const known =
    pending && pending.callId === incoming.callId && pending.peerId === incoming.peerId
      ? pending
      : null;

  // A repeat that overtook the decline or hangup that ended this call. Without
  // this the ended screen is replaced by the same call ringing again, seconds
  // after it was refused.
  if (mine && state.phase === 'ended') return 'ignore';

  // Any offer for the call already on this screen is that call, whatever it
  // says. `idle` belongs here too: the provider's view of its own state is a
  // render behind the ring it has just dispatched, so an offer arriving in that
  // window sees a phase that has not heard of the call yet — and reading that
  // as a new one is how a single call came to ring twice.
  if (known && (state.phase === 'ringing' || state.phase === 'idle')) return 'refresh';

  if (known && sameIceSession(known.sdp, incoming.sdp)) {
    // They are still asking, which means the answer we sent never arrived —
    // the caller stops repeating the instant it lands. A phone that was
    // unlocked to answer rebuilds its realtime socket at exactly that moment,
    // and one lost broadcast otherwise costs the whole call.
    if (mine && state.phase === 'connecting') return 'replay-answer';
    return 'refresh';
  }

  // The offer this device has been waiting for since the user answered on the
  // lock screen. It is the first one for this call, not an ICE restart — there
  // is no connection to restart — so it goes to the ring path, which answers it
  // immediately because the decision was already taken.
  if (mine && !connected && state.phase === 'connecting') return 'ring';

  if (mine && (state.phase === 'connecting' || state.phase === 'active')) return 'restart';

  if (state.phase !== 'idle' && state.phase !== 'ended') {
    // Both of us dialled at once. Exactly one side yields, decided the same way
    // on both phones with no extra round trip. The other must stay quiet rather
    // than reply busy, which would end both calls.
    if (state.phase === 'dialing' && state.peerId === incoming.peerId) {
      return polite ? 'yield' : 'ignore';
    }
    return 'busy';
  }

  return 'ring';
}
